apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres-ha
data:
  PATRONI_POSTGRESQL_PG_HBA: |
    host all all 0.0.0.0/0 trust
    host replication replicator 0.0.0.0/0 trust
